site_name: Name of the ARISE course
nav:
    - Description of the course: index.md
    - Course Content:
      - "1. title of first chapter": chapters/chapter_01.md
      - "2. title of second chapter": chapters/chapter_02.md
      - "3. title of third chapter" : chapters/chapter_03.md
      - "4. title of fourth chapter": chapters/chapter_examples_styles.md
      - "References": chapters/references.md
    - "Follow up training": follow_up_training.md

theme:
  name: material
  logo: assets/images/ARISE2_logo_RGB.png
  favicon: assets/images/ARISE2_logo_RGB.png
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.footer
    - toc.integrate
  font: 
    text: Lato

# Repository
repo_name: ricapacity/Template_for_ARISE2_materials
repo_url: https://ricapacity.github.io/Template_for_ARISE2_materials/
edit_uri: edit/main/docs/

plugins:
  - tags:
      tags_file: keywords.md
  - search
  - bibtex:
      bib_file: "references.bib"
  - mkdocs-video # embed videos to the docs

  
# Footer
copyright: Creation of these materials was initially funded by  the ARISE and ARISE2 programs,  EC MSCA Cofund grants under Grant agreements numbers XXXXX and XXXXX. Materials are made availiable under a CC-BY 4.0 licence 

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc:
      toc_depth: 3
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - neoteroi.cards
  - addbioschemas

extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css
